language: python
python:
  - "3.6"

services:
  - mysql

env:
  -DJANGO=2.1 DB=mysql

install:
  - pip install -r requirements.txt
  - pip install psycopg2


before_script:
  - cd app && python manage.py wait_for_db && python manage.py migrate

script:
  - python manage.py test && flake8
