language: python
python:
  - "3.6"

services:
  - postgresql

env:
  -DJANGO=2.1 DB=postgresql
  global:
    - PGPORT=5433

addons:
  postgresql: "9.6"

install:
  - pip install -r requirements.txt


before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd app && python manage.py wait_for_db && python manage.py migrate

script:
  - python manage.py test && flake8
