language: python
python:
  - "3.6"

services:
  - postgresql

env:
  -DJANGO=2.1 DB=postgresql

install:
  - pip install -r requirements.txt
  - pip install psycopg2


before_script:
  - psql -c 'create database database1;' -U postgres
  - cd app
  - python manage.py wait_for_db

script:
  - python manage.py test && flake8
